// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYT4xcaWa-7MCt4bX0_AbxQ7d-3GkwxA',
    appId: '1:965889901162:web:07d24a7d02a535d2b78013',
    messagingSenderId: '965889901162',
    projectId: 'muevelo-8e4a9',
    authDomain: 'muevelo-8e4a9.firebaseapp.com',
    storageBucket: 'muevelo-8e4a9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrOVznpYkNCcF97hmPB5xgZPmgGaN31bM',
    appId: '1:965889901162:android:1c680f99c21c0bb0b78013',
    messagingSenderId: '965889901162',
    projectId: 'muevelo-8e4a9',
    storageBucket: 'muevelo-8e4a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwYT4xcaWa-7MCt4bX0_AbxQ7d-3GkwxA',
    appId: '1:965889901162:web:a115f87bc32a2423b78013',
    messagingSenderId: '965889901162',
    projectId: 'muevelo-8e4a9',
    authDomain: 'muevelo-8e4a9.firebaseapp.com',
    storageBucket: 'muevelo-8e4a9.firebasestorage.app',
  );
}
